class HomeController < ApplicationController
  def index
    mock = Mock.find_by_path(request.fullpath)
    render json: mock.content , status: mock.status
  rescue
    flash[:alert] = "Mock \"#{request.fullpath}\" não encontrado"
    redirect_to mocks_path
  end
end

# [{"id"=>nil,
#   "product_name"=>"Banco de dados compartilhado",
#   "product_api_prefix"=>"HOST",
#   "product_api_answered"=>true,
#   "config_items"=>[],
#   "done"=>true,
#   "customer"=>"omnitrix"},
#  {"id"=>nil,
#   "product_name"=>"Estoque",
#   "product_api_prefix"=>"ESTQ",
#   "product_api_answered"=>false,
#   "config_items"=>[],
#   "done"=>true,
#   "customer"=>"omnitrix"},
#  {"id"=>nil,
#   "product_name"=>"Revenda",
#   "product_api_prefix"=>"RESL",
#   "product_api_answered"=>true,
#   "config_items"=>
#    ["gagarin0178",
#     "gagarin0179",
#     "gagarin0180",
#     "cpanelqa0001",
#     "gagarin0181",
#     "gagarin0182",
#     "gagarin0184",
#     "gagarin0186",
#     "gagarin0187",
#     "gagarin0188",
#     "gagarin0195",
#     "gagarin0197",
#     "gagarin0198",
#     "gagarin0199",
#     "gagarin0201",
#     "gagarin0202",
#     "gagarin0203",
#     "gagarin0204",
#     "gagarin0205",
#     "gagarin0206",
#     "gagarin0208",
#     "gagarin0209",
#     "pleskwqa0001",
#     "gagarin0216",
#     "gagarin0217",
#     "gagarin0218",
#     "gagarin0219",
#     "gagarin0314",
#     "gagarin0315",
#     "gagarin0317"],
#   "done"=>true,
#   "customer"=>"omnitrix"},
#  {"id"=>nil,
#   "product_name"=>"Revenda Revendinha",
#   "product_api_prefix"=>"RRES",
#   "product_api_answered"=>false,
#   "config_items"=>[],
#   "done"=>true,
#   "customer"=>"omnitrix"},
#  {"id"=>nil,
#   "product_name"=>"Teste",
#   "product_api_prefix"=>"TEST",
#   "product_api_answered"=>false,
#   "config_items"=>[],
#   "done"=>true,
#   "customer"=>"omnitrix"},
#  {"id"=>nil,
#   "product_name"=>"VPS Locaweb",
#   "product_api_prefix"=>"LVPS",
#   "product_api_answered"=>false,
#   "config_items"=>[],
#   "done"=>true,
#   "customer"=>"omnitrix"},
#  {"id"=>nil,
#   "product_name"=>"system integration",
#   "product_api_prefix"=>"SYSINT",
#   "product_api_answered"=>false,
#   "config_items"=>[],
#   "done"=>true,
#   "customer"=>"omnitrix"}]